config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

#   devise_for :users, path: 'users', controllers: {
#   sessions:      'users/sessions',
#   passwords:     'users/passwords',
#   registrations: 'users/registrations',
#   omniauth_callbacks: 'users/omniauth_callbacks'
# }

  devise_for :admins, path: 'admins', controllers: {
  sessions:      'admins/sessions',
  passwords:     'admins/passwords',
  registrations: 'admins/registrations'
}

  devise_scope :user do
    authenticated :user do
      root :to => 'users#show', as: :authenticated_user_root
    end
    unauthenticated :user do
      root :to => 'users/sessions#new', as: :unauthenticated_user_root
    end
  end

  devise_scope :admin do
    authenticated :admin do
      root :to => 'admins#show', as: :authenticated_admin_root
    end
    unauthenticated :admin do
      root :to => 'admins/sessions#new', as: :unauthenticated_admin_root
    end
  end

  # namespace :admins do
  #   constraints subdomain: 'admins' do
  #     resources :users, only: [:index, :destroy] do
  #       collection do
  #         get 'search'
  #       end
  #     end
  #   end
  # end

  resources :admins, only: [:show] do
    collection do
      get 'search'
    end
  end

  resources :admins_users, only: [:show]

 	resources :users, only: [:show, :edit, :update,] do
    resources :next_lessons, only: [:create, :update]
	  resources :users_lessons, only: [:create, :update]
	  resources :users_interviews, only: [:create, :update]
 	  resources :users_insights, only: [:create, :update]
    resources :users_exams, only: [:create, :update]
    resources :users_practices, only: [:create, :update]
    resources :users_expeditions, only: [:create, :update]
    resources :pictures, only: [:index, :new, :create]
  end

  # resources :insights, only: [:edit, :update]

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :timeoutable

end

app/models/exam.rb
class Exam < ActiveRecord::Base

	has_many :users_exams
	has_many :users, through: :users_exams

end

app/models/expedition.rb
class Expedition < ActiveRecord::Base

	has_many :users_expeditions
	has_many :users, through: :users_expeditions

end

app/models/insight.rb
class Insight < ActiveRecord::Base

	has_many :users_insights

	has_many :users, through: :users_insights	

end

app/models/interview.rb
class Interview < ActiveRecord::Base

	has_many :users_interviews
	has_many :users, through: :users_interviews

end

app/models/lesson.rb
class Lesson < ActiveRecord::Base

	has_many :users_lessons
	has_many :users, through: :users_lessons


end

app/models/next_lesson.rb
class NextLesson < ActiveRecord::Base

	belongs_to :user
	validates_presence_of :user_id, :date_time

  def self.students(next_lessons)
    no_appointments = []
    
    next_lessons.each do |next_lesson|
      require "date"
      if next_lesson.date_time < Date.yesterday && next_lesson.updated_at > Date.today.months_ago(2)
        no_appointments << next_lesson.user_id
      end
    end
    return no_appointments
  end

  def self.coming(next_lessons)
    comingstudents_ids = []

    next_lessons.each do |next_lesson|
      require "date"
      if next_lesson.date_time < Date.today + 7.day && next_lesson.date_time > Date.yesterday
        comingstudents_ids << next_lesson.user_id
      end
    end
    return comingstudents_ids
  end

end

app/models/picture.rb
class Picture < ActiveRecord::Base

  belongs_to :user
  validates_presence_of :user_id, :image

  mount_uploader :image, ImageUploader
  
end

app/models/practice.rb
class Practice < ActiveRecord::Base

	has_many :users_practices
	has_many :users, through: :users_practices

end

app/models/progress_bar.rb
class ProgressBar
  include ActiveModel::Model

  def self.table_records(user)

    lessons = UsersLesson.accomplished(user)
  	interviews = UsersInterview.accomplished(user)
  	insights = UsersInsight.accomplished(user)
  	exams = UsersExam.accomplished(user)
  	practices = UsersPractice.accomplished(user)
  	expeditions = UsersExpedition.accomplished(user)
  	records = lessons + interviews + insights + exams + practices + expeditions
  	progress = (records.to_f / 39 * 100).to_i
  	return progress

  end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable, :omniauthable, :omniauth_providers => [:facebook]

  has_many :lessons, through: :users_lessons
  has_many :users_lessons

  has_many :interviews, through: :users_interviews
  has_many :users_interviews

  has_many :insights, through: :users_insights
  has_many :users_insights

  has_many :exams, through: :users_exams
  has_many :users_exams

  has_many :practices, through: :users_practices
  has_many :users_practices

  has_one  :next_lesson

  has_many :expedition, through: :users_expeditions
  has_many :users_expeditions

  has_many :pictures

  # has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>"}
  # validates_attachment_content_type :avatar, content_type: ["image/jpg","image/jpeg","image/png"]

  mount_uploader :image, ImageUploader


  def self.from_omniauth(auth)
    User.find_or_create_by(provider: auth["provider"], uid: auth["uid"]) do |user|
      user.provider = auth["provider"]
      user.uid = auth["uid"]
      user.name = auth["info"]["nickname"] || auth["info"]["name"]
      user.birthday = auth["info"]["birthday"]
      user.image = auth["info"]["image"]
      auth["info"]["email"] ? user.email = auth["info"]["email"] : user.email = User.dummy_email(auth)
      user.password   = Devise.friendly_token[0, 20]
      user.skip_confirmation!
    end
  end

  # def self.from_omniauth(auth)
  #   user = User.where(email: auth.info.email).first
  #   if user
  #     return user
  #   else
  #     where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
  #       # userモデルが持っているカラムをそれぞれ定義していく
  #       user.email = auth.info.email
  #       user.password = Devise.friendly_token[0,20]
  #       user.name = auth.info.name
  #       user.avatar = auth.info.image
  #       user.uid = auth.uid
  #       user.provider = auth.provider

  #       # If you are using confirmable and the provider(s) you use validate emails,
  #       # uncomment the line below to skip the confirmation emails.
  #       user.skip_confirmation!
  #     end
  #   end
  # end

  def full_profile?
    image? && name? && name_kana? && tel?
  end

  def self.search(search) #self.でクラスメソッドとしている
    if search # Controllerから渡されたパラメータが!= nilの場合は、name_kanaカラムを部分一致検索
      User.where(['name_kana LIKE ?', "%#{search}%"])
    else
      User.all #全て表示。
    end
  end

end


private

  def self.dummy_email(auth)
    "#{auth.uid}-#{auth.provider}@example.com"
  end

app/models/users_exam.rb
class UsersExam < ActiveRecord::Base

	belongs_to :user
	belongs_to :exam

	validates_presence_of :user_id, :exam_id, :date

	delegate :name, to: :exam
	scope :accomplished, ->(user) { where(user_id: user.id).length }

end

app/models/users_insight.rb
class UsersInsight < ActiveRecord::Base

	belongs_to :user
	belongs_to :insight

	validates_presence_of :user_id, :insight_id, :date

	delegate :name, to: :insight
	scope :accomplished, ->(user) { where(user_id: user.id).length }

end

app/models/users_interview.rb
class UsersInterview < ActiveRecord::Base

	belongs_to :user
	belongs_to :interview

	validates_presence_of :user_id, :interview_id, :date

	delegate :name, to: :interview
	scope :accomplished, ->(user) { where(user_id: user.id).length }

end

app/models/users_lesson.rb
class UsersLesson < ActiveRecord::Base

	belongs_to :user
	belongs_to :lesson

	validates_presence_of :user_id, :lesson_id, :date

	delegate :name, to: :lesson
	scope :accomplished, ->(user) { where(user_id: user.id).length }

end

app/models/users_practice.rb
class UsersPractice < ActiveRecord::Base

	belongs_to :user
	belongs_to :practice

	validates_presence_of :user_id, :practice_id, :date

	scope :accomplished, ->(user) { where(user_id: user.id).length }
	scope :done_date, ->(user) { find_by(user_id: user.id).date }

end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/insights_helper.rb
module InsightsHelper
end

app/helpers/pictures_helper.rb
module PicturesHelper
end

app/helpers/users_helper.rb
module UsersHelper
#   def lesson_date(lesson, user)
#     lesson.users_lessons.where(user_id: user.id).first.date
#   end

end

app/views/admins/_header.html.erb
<nav class='navbar is-black' role="navigation" aria-label="main navigation">
  <div class='container'>
    <div class='navber-brand'>
      <a class="navbar-item" href="http://www.251media.jp/?utm_source=kanataw&utm_medium=banner">
        <%= image_tag("251_logo.jpeg", size: "", alt: "251 media") %>
      </a>
    </div>
      <span class='navbar-burger burger' data-target="navbarMenu">
      </span>
    <div class="navbar-menu is-active">
      <div class="navbar-end">
        <a><%= link_to 'Admin Home', admin_path(current_admin), class: "navbar-item is-active"%></a>
        <a><%= link_to "Sign Out", destroy_admin_session_path, method: :delete, class: "navbar-item is-active"%></a>
      </div>
    </div>
  </div>
</nav>

app/views/admins/search.html.erb
<section class="hero is-fullheight">
	<div class='container'>
		<div class="hero-body">
			<div class="column is-4 is-offset-4">
				<h3 class="subtitle"><strong>検索結果</strong></h3>		
					<% @users.each do |user| %>
						生徒名：
						<%= link_to "#{user.name}", admins_user_path(user.id) %><br/>
						<br>
						<%= image_tag user.image.url %>
						<br>
						電話番号：
						<%= user.tel %><br/>
						<br>
						Emailアドレス：
						<p><%= user.email%></p>
						<br>
						次回授業時間：
						<%= user.has_next_lesson %>
						<br>
						前回授業：
						<%= user.has_lessons %>
						<br>
						10ケースマラソン：
						<%= user.has_interviews %>
						<br>
						12示唆マラソン：
						<%= user.has_insights %>
						<br>
						考えるエンジン検定：
						<%= user.has_exams %>
						<br>
					<% end %>
			</div>
		</div>
	</div>
</section>

app/views/admins/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/admins/show.html.erb
<section class="hero is-medium">
	<div class='container'>
		<div class='block'>
		</div>
		<div class="field has-addons box">
		    <div class='control is-expanded'>
		    <%= form_tag('/admins/search', method: :get) do %>
		    <%= text_field_tag :search, params[:search], :class => 'input is-success', placeholder: "フリガナで生徒検索" %>
		    </div>
		    <div class="control">
		    <%= submit_tag "Search", :name => nil, :class => 'button is-link' %>
		    </div>
		    <% end %>
			</div>
		</div>
	</div>
</section>

<section class="section is-clearfix">
  <div class='container'>
  	<p class='subtitle has-text-danger has-text-centered '>次回予約未定の生徒</p>
  	  <div class='level'>
  	  	<div class='level-item'>
			  <% @forgotten_users.each do |forgotten_user| %>
				  <p class='subtitle has-text-centered '><%=link_to "#{forgotten_user.name}", admins_user_path(forgotten_user.id) %>/</p>
			  <% end %>
			  </div>
		  </div>
	  <nav class="pagination" role="navigation" aria-label="pagination">
		  <%= paginate @forgotten_users, :param_name => 'forgotten_page' %>
	  </nav>
	</div>
</section>

<section class="section is-clearfix">
<p class='subtitle has-text-danger has-text-centered '>生徒情報</p>
  <div class='row columns'>
  	<% @coming_users.each do |user| %>
  	  <div class='column is-2'>
  	  	<div class='card large'>
  	  		<div class='card-image'>
  	  			<figure class="image">
				      <%= image_tag user.image.url %>
				    </figure>
				  </div>
				  <div class='card-content'>
  				  <p class='subtitle has-text-centered'><%=link_to "#{user.name}", admins_user_path(user.id) %></p>
				    <p>電話番号:</p>
				    <p><%= user.tel %></p><br>
				   
	 				  <p>次回授業時間:</p>
					  <%= user.has_next_lesson %>
				    <br>

				    <p>前回授業:</p>
					  <%= user.has_lessons %>
				    <br>

					  <p>10ケースマラソン:</p>
					  <%= user.has_interviews %>
				    <br>

				    <p>12示唆マラソン:</p>
					  <%= user.has_insights %>
				    <br>

				    <p>考えるエンジン検定:</p>
						<%= user.has_exams%>
	
					  <br>
					</div>
		    </div>
		  </div>
		  <% end %>
		</div>
	<nav class="pagination" role="navigation" aria-label="pagination">
    <%= paginate @coming_users, :param_name => 'user_page' %>
  </nav>
</section>

app/views/common/_header.html.erb
<% if user_signed_in? %>
  <div class='navbar navbar-default navbar-fixed-top'>
    <div class='container'>
      <div class='hidden-xs hidden-sm'>
      考えるエンジン講座
      </div>
      <div class='navbar-collapse collapse navbar-responsive-collapse navbar-right'>
        <ul class='nav navbar-nav'>
          <li><%= link_to 'HOME', root_path %></li>
          <li class='dropdown'>
            <a href='#' class='dropdown-toggle' data-toggle='dropdown' role='button' aria-expanded='false'>Profile<span class='caret'></span></a>
            <ul class='dropdown-menu' role='menu'>
              <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
            </ul>
          </li>
        </ul>
      </div>
    </div>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <script src="https://code.jquery.com/jquery-3.0.0.min.js"></script>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bulma/0.7.1/css/bulma.min.css">
  <script defer src="https://use.fontawesome.com/releases/v5.0.7/js/all.js"></script>
  
  <title>考えるエンジン講座</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>

<body>
    <% if current_user %>
      <%= render partial: 'users/header' %>
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
    <% elsif current_admin %>
      <%= render partial: 'admins/header' %>
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
    <% end %>
    <%= yield %>

    <footer class="footer">
      <div class="container">
        <div class="content has-text-centered">
        <p>
          <strong>考えるエンジン講座</strong> by <a href="http://kanata-win.jp/">株式会社 KANATA</a>
        </p>
        </div>
      </div>
    </footer>
</body>
</html>