config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

#   devise_for :users, path: 'users', controllers: {
#   sessions:      'users/sessions',
#   passwords:     'users/passwords',
#   registrations: 'users/registrations',
#   omniauth_callbacks: 'users/omniauth_callbacks'
# }

  devise_for :admins, path: 'admins', controllers: {
  sessions:      'admins/sessions',
  passwords:     'admins/passwords',
  registrations: 'admins/registrations'
}

  devise_scope :user do
    authenticated :user do
      root :to => 'users#show', as: :authenticated_user_root
    end
    unauthenticated :user do
      root :to => 'users/sessions#new', as: :unauthenticated_user_root
    end
  end

  devise_scope :admin do
    authenticated :admin do
      root :to => 'admins#show', as: :authenticated_admin_root
    end
    unauthenticated :admin do
      root :to => 'admins/sessions#new', as: :unauthenticated_admin_root
    end
  end

  # namespace :admins do
  #   constraints subdomain: 'admins' do
  #     resources :users, only: [:index, :destroy] do
  #       collection do
  #         get 'search'
  #       end
  #     end
  #   end
  # end

  resources :admins, only: [:show] do
    collection do
      get 'search'
    end
  end

  resources :admins_users, only: [:show]

 	resources :users, only: [:show, :edit, :update,] do
    resources :next_lessons, only: [:create, :update]
	  resources :users_lessons, only: [:create, :update]
	  resources :users_interviews, only: [:create, :update]
 	  resources :users_insights, only: [:create, :update]
    resources :users_exams, only: [:create, :update]
    resources :users_practices, only: [:create, :update]
    resources :users_expeditions, only: [:create, :update]
    resources :pictures, only: [:index, :new, :create]
  end

  # resources :insights, only: [:edit, :update]

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable, :omniauthable, :omniauth_providers => [:facebook]

  has_many :lessons, through: :users_lessons
  has_many :users_lessons

  has_many :interviews, through: :users_interviews
  has_many :users_interviews

  has_many :insights, through: :users_insights
  has_many :users_insights

  has_many :exams, through: :users_exams
  has_many :users_exams

  has_many :practices, through: :users_practices
  has_many :users_practices

  has_one  :next_lesson

  has_many :expedition, through: :users_expeditions
  has_many :users_expeditions

  has_many :pictures

  # has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>"}
  # validates_attachment_content_type :avatar, content_type: ["image/jpg","image/jpeg","image/png"]

  mount_uploader :image, ImageUploader


  def self.from_omniauth(auth)
    User.find_or_create_by(provider: auth["provider"], uid: auth["uid"]) do |user|
      user.provider = auth["provider"]
      user.uid = auth["uid"]
      user.name = auth["info"]["nickname"] || auth["info"]["name"]
      user.birthday = auth["info"]["birthday"]
      user.image = auth["info"]["image"]
      auth["info"]["email"] ? user.email = auth["info"]["email"] : user.email = User.dummy_email(auth)
      user.password   = Devise.friendly_token[0, 20]
      user.skip_confirmation!
    end
  end

  # def self.from_omniauth(auth)
  #   user = User.where(email: auth.info.email).first
  #   if user
  #     return user
  #   else
  #     where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
  #       # userモデルが持っているカラムをそれぞれ定義していく
  #       user.email = auth.info.email
  #       user.password = Devise.friendly_token[0,20]
  #       user.name = auth.info.name
  #       user.avatar = auth.info.image
  #       user.uid = auth.uid
  #       user.provider = auth.provider

  #       # If you are using confirmable and the provider(s) you use validate emails,
  #       # uncomment the line below to skip the confirmation emails.
  #       user.skip_confirmation!
  #     end
  #   end
  # end

  def full_profile?
    image? && name? && name_kana? && tel?
  end

  def self.search(search) #self.でクラスメソッドとしている
    if search # Controllerから渡されたパラメータが!= nilの場合は、name_kanaカラムを部分一致検索
      User.where(['name_kana LIKE ?', "%#{search}%"])
    else
      User.all #全て表示。
    end
  end

end


private

  def self.dummy_email(auth)
    "#{auth.uid}-#{auth.provider}@example.com"
  end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController

  def facebook
    authorize
  end

  # def callback_from(provider)
  #   provider = provider.to_s

  #   @user = User.find_for_oauth(request.env['omniauth.auth'])

  #   if @user.persisted?
  #     flash[:notice] = I18n.t('devise.omniauth_callbacks.success', kind: provider.capitalize)
  #     sign_in_and_redirect @user, event: :authentication
  #   else
  #     session["devise.#{provider}_data"] = request.env['omniauth.auth']
  #     redirect_to new_user_registration_url
  #   end
  # end

  private

    def authorize
      @user = User.from_omniauth(request.env["omniauth.auth"].except("extra"))
      
      if @user.persisted?
        sign_in_and_redirect @user, event: :authentication
        set_flash_message(:notice, :success, kind: "Facebook") if is_navigational_format?
      else
        session["devise.user_data"] = @user.attributes
        redirect_to new_user_registration_url
      end
    end
end  

    # You need to implement the method below in your model (e.g. app/models/user.rb)
  #   @user = User.from_omniauth(request.env["omniauth.auth"])

  #   if @user.persisted?
  #     sign_in_and_redirect @user, :event => :authentication #this will throw if @user is not activated
  #     set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
  #   else
  #     session["devise.facebook_data"] = request.env["omniauth.auth"]
  #     redirect_to new_user_registration_url
  #   end
  # end

  # def failure
  #   redirect_to new_user_session_path
  # end
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  #   binding.pry
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :authenticate_user!
	before_action :move_to_session

	def show
		unless current_user.full_profile?
			redirect_to edit_user_path(current_user)
		else
			user_path(current_user)
		end

		# @user = User.find(params[:id])

		@progress = ProgressBar.table_records(@user)

		@lessons = Lesson.includes(:users_lessons)
		@users_lesson = UsersLesson.new

		@interviews = Interview.includes(:users_interviews)
		@users_interview = UsersInterview.new

		@insights = Insight.includes(:users_insights)
		@users_insight = UsersInsight.new

		@exams = Exam.includes(:users_exams)
		@users_exam = UsersExam.new

		@next_lesson = NextLesson.new

		@practices = Practice.includes(:users_practices)
		@users_practice = UsersPractice.new

		@expeditions = Expedition.includes(:users_expeditions)
		@users_expedition = UsersExpedition.new

	end

  def edit
		# @user = User.find(params[:id])
  end

	def update
		# @user = User.find(params[:id])

  	respond_to do |format|
    if current_user.update(update_params)
        format.html { redirect_to user_path(current_user), notice: 'ユーザー情報が正しく登録されました' }
      else
        format.html { redirect_to edit_user_path(current_user) }
      end
		end
		
		# @users_insight = @user.users_insights.find_by(insight_id: params[:user][:users_insight][:insight_id])
		# @users_insight.update(date: insight_update_params[:users_insight][:date])
		# redirect_to user_path(current_user)
		# if current_user
    #   respond_to do |format|
    #     if @users_insight.update(insight_update_params)
    #       format.html { redirect_to user_path(current_user), notice: 'Date was successfully updated.' }
    #     else
    #       format.html { redirect_to user_path(current_user) }
    #     end
    #   end
    # else
    #   respond_to do |format|
    #     if @users_insight.update(insight_update_params)
    #       format.html { redirect_to admins_user_path(params[:user_id]), notice: 'Date was successfully updated.' }
    #     else
    #       format.html { redirect_to admins_user_path(params[:user_id]) }
    #     end
    #   end
    # end

  end

  private	
	def move_to_session
		@user = User.find(params[:id])
		unless current_user.id == @user.id
			redirect_to action: 'show', status: 404
		end
	end

	def update_params
  	params.require(:user).permit(:name, :name_kana, :birthday, :tel, :job, :image)
	end

  def insight_update_params
    params.require(:user).permit(users_insight: [:date, :insight_id])
  end
end

app/helpers/users_helper.rb
module UsersHelper
#   def lesson_date(lesson, user)
#     lesson.users_lessons.where(user_id: user.id).first.date
#   end

end

app/views/users/_exam.html.erb
		<div class='column is-fullwidth-mobile is-4-tablet is-offset-1-tablet is-4-desktop is-offset-1-desktop box'>
			<div class='title is-size-5-mobile is-size-5-tablet is-size-4-desktop has-text-centered'>考えるエンジン検定</div>
				<% exams.each_with_index do |exam, i| %>
				  <ul>
					  <div class='subtitle is-size-5 has-text-centered'><%= exam.name %></div>
						<%# <%= exam.has_exam(user, users_exam, exam, i) %> 
				  	<% if exam.users_exams.exists?(user_id: user.id) %>
						 	<div class='subtitle is-size-5 has-text-link has-text-centered'><%= exam.exam_date(user) %></div>
							<p class='has-text-centered'>
							  <a class="button is-link modal-button 04" id="modal-btn<%= i %>" data-index=<%= i %>>受検日変更</a>	
							</p>
						 	<div class='block'></div>

							<div id="users-exam-modal<%= i %>" class="modal">
							<div class="modal-background"></div>
							<div class="modal-content box has-text-centered">
								<p class="subtitle">考えるエンジン検定：<%= exam.name %></p>
									<%# form_forのurlでcontrollerとactionを指定する %>
									<%= form_for exam.exam_of_user(user), url: user_users_exam_path(user_id: user.id, id: exam.users_exam_id(user)), html: {method: 'PATCH'}, remote: true do |f| %>  
										<div class="field has-addons">  				
												<%= f.date_field :date, :class => "input is-info", value: Time.now.strftime("%Y-%m-%d") %>								
												<%= f.hidden_field :exam_id, :value => exam.id %>
											<div class="control">
												<%= f.submit '受検日変更', :class => 'button is-link'%>
											</div>
										</div>
									<% end %>
							</div>
							<button class="modal-close is-large" aria-label="close" data-dismiss="modal"></button>
							</div>
							
				  	<% else %>
			        <%= render partial: "users/examModal", locals: { user: user, users_exam: users_exam, exam: exam, i: i } %>
						<% end %>
					</ul>
			  <% end %>
		</div>

app/views/users/_examModal.html.erb
					  		<p class='has-text-centered'>
		 					    <a class="button is-danger modal-button 04" id="modal-btn<%= i %>" data-index=<%= i %>>受検日登録</a>
		 					    <div class='block'></div>
		            </p>
								  <div id="users-exam-modal<%= i %>" class="modal">
		  						  <div class="modal-background"></div>
		  							<div class="modal-content box has-text-centered">
      							  <p class="subtitle">考えるエンジン検定：<%= exam.name %></p>
										  	<%= form_for [user, users_exam], remote: true do |f| %>
								  				<div class="field has-addons">
										    		<%= f.date_field :date, :class => "input is-info", value: Time.now.strftime("%Y-%m-%d") %>
										        <%= f.hidden_field :exam_id, :value => exam.id %>
										        <div class="control">
										        <%= f.submit '受検日登録', :class => 'button is-danger' %>
										        </div>
										      </div>
								          <% end %>
							 			</div>
							 			<button class="modal-close is-large"></button>
					 			    </div>

app/views/users/_expedition.html.erb
		<div class="column is-fullwidth-mobile is-one-thirds-tablet is-4-desktop is-offset-1-desktop box">
			<div class='title is-size-5-mobile is-size-5-tablet is-size-4-desktop has-text-centered'>続・考えるエンジン講座</div>
			<% expeditions.each_with_index do |expedition, i| %>
			  <ul>
				  <div class='subtitle is-size-5 has-text-centered'><%= expedition.name %></div>
				  	<% if expedition.users_expeditions.exists?(user_id: user.id) %>
						 	<div class='subtitle is-size-5 has-text-link has-text-centered'><%= expedition.expedition_date(user) %></div>
							<p class='has-text-centered'>
							  <a class="button is-link modal-button 06" id="modal-btn<%= i %>" data-index=<%= i %>>受講日変更</a>	
							</p>
						 	<div class='block'></div>
							
							<div id="users-expedition-modal<%= i %>" class="modal">
							<div class="modal-background"></div>
							<div class="modal-content box has-text-centered">
								<p class="subtitle"><%= expedition.name %></p>
									<%# form_forのurlでcontrollerとactionを指定する %>
									<%= form_for expedition.expedition_of_user(user), url: user_users_expedition_path(user_id: user.id, id: expedition.users_expedition_id(user)), html: {method: 'PATCH'}, remote: true do |f| %>  
										<div class="field has-addons">  				
												<%= f.date_field :date, :class => "input is-info", value: Time.now.strftime("%Y-%m-%d") %>								
												<%= f.hidden_field :expedition_id, :value => expedition.id %>
											<div class="control">
												<%= f.submit '実施日変更', :class => 'button is-link'%>
											</div>
										</div>
									<% end %>
							</div>
							<button class="modal-close is-large" aria-label="close" data-dismiss="modal"></button>
							</div>

				  	<% else %>
							<p class='has-text-centered'>
		 					  <a class="button is-danger modal-button 06" id="modal-btn<%= i %>" data-index=<%= i %>>受講日登録</a>
		 					  <div class='block'></div>
		          </p>
								  <div id="users-expedition-modal<%= i %>" class="modal">
		  						  <div class="modal-background"></div>
		  							<div class="modal-content box has-text-centered">
      							  <p class="subtitle"><%= expedition.name %></p>
										  	<%= form_for [user, users_expedition], remote: true do |f| %>
													<div class="field has-addons">
														<%= f.date_field :date, :class => "input is-info", value: Time.now.strftime("%Y-%m-%d") %>			      
														<%= f.hidden_field :expedition_id, :value => expedition.id %>
														<div class="control">
															<%= f.submit '受講日登録', :class => 'button is-danger'%>
														</div>
													</div>
												<% end %>
							 			</div>
							 			<button class="modal-close is-large" aria-label="close" data-dismiss="modal"></button>
					 			  </div>
						<% end %>
				</ul>
		  <% end %>
	  </div>

app/views/users/_header.html.erb
<nav class='navbar is-black is-mobile'>
  <div class='container'>
    <div class='navber-brand'>
      <a class="navbar-item" href="http://www.251media.jp/">
        <img src="https://pbs.twimg.com/profile_images/925583780252753920/ny_dUqtG_400x400.jpg" alt: "251 media">
      </a>
      <div class="navbar-burger burger" data-target="navbar-menu-id">
        <span aria-hidden="true"></span>
        <span aria-hidden="true"></span>
        <span aria-hidden="true"></span>
      </div>
    </div>

    <div id="navbar-menu-id"  class="navbar-menu">

      <div class="navbar-end">
        <a><%= link_to 'HOME', user_path(current_user), class: "navbar-item" %></a>
        <div class="navbar-item has-dropdown is-hoverable">
          <div class="navbar-link"><%= "#{current_user.name}" %></div>
          <div class="navbar-dropdown">
            <a><%= link_to "Profile", edit_user_path(current_user), class: "navbar-item" %></a>
            <a><%= link_to "Photo Album", user_pictures_path(current_user), class: "navbar-item" %></a>
          </div>
        </div>
        <a><%= link_to "Sign Out", destroy_user_session_path, method: :delete, class: "navbar-item" %></a>
      </div>
    </div>
  </div>
</nav>

app/views/users/_insight.html.erb
	  <div class='column is-2-tablet is-offset-1-tablet is-2-desktop is-offset-1-desktop is-fullwidth-mobile box'>
		  <div class='title is-size-5-mobile is-size-6-tablet is-size-4-desktop has-text-centered'>12示唆マラソン</div>
		  <% insights.each_with_index do |insight, i| %>
		    <div>
			    <div class='subtitle is-size-5 has-text-centered'><%= insight.name %></div>
				  	<% if insight.users_insights.exists?(user_id: user.id) %>
				  	  <div class='subtitle is-size-5 has-text-link has-text-centered'><%= insight.insight_date(user) %></div>
							<p class='has-text-centered'>
							  <a class="button is-link modal-button 03" id="modal-btn<%= i %>" data-index=<%= i %>>実施日変更</a>	
							</p>
				  	  <div class='block'></div>

							<div id="users-insight-modal<%= i %>" class="modal">
							<div class="modal-background"></div>
							<div class="modal-content box has-text-centered">
								<p class="subtitle">12示唆マラソン：<%= insight.name %></p>
									<%# form_forのurlでcontrollerとactionを指定する %>
									<%= form_for insight.insight_of_user(user), url: user_users_insight_path(user_id: user.id, id: insight.users_insight_id(user)), html: {method: 'PATCH'}, remote: true do |f| %>  
										<div class="field has-addons">  				
												<%= f.date_field :date, :class => "input is-info", value: Time.now.strftime("%Y-%m-%d") %>								
												<%= f.hidden_field :insight_id, :value => insight.id %>
											<div class="control">
												<%= f.submit '実施日変更', :class => 'button is-link'%>
											</div>
										</div>
									<% end %>
							</div>
							<button class="modal-close is-large" aria-label="close" data-dismiss="modal"></button>
							</div>

				  	<% else %>
							<p class='has-text-centered'>
		 					  <a class="button is-danger modal-button 03" id="modal-btn<%= i %>" data-index=<%= i %>>実施日登録</a>
		 					  <div class='block'></div>
		          </p>
								  <div id="users-insight-modal<%= i %>" class="modal">
		  						  <div class="modal-background"></div>
		  							<div class="modal-content box has-text-centered">
      							  <p class="subtitle">12示唆マラソン：<%= insight.name %></p>
										  	<%= form_for [user, users_insight], remote: true do |f| %>
								  				<div class="field has-addons">
										    		  <%= f.date_field :date, :class => "input is-info", value: Time.now.strftime("%Y-%m-%d") %>
										          <%= f.hidden_field :insight_id, :value => insight.id %>
										        <div class="control">
										          <%= f.submit '実施日登録', :class => 'button is-danger'%>
										        </div>
										      </div>
								        <% end %>
							 			</div>
							 			<button class="modal-close is-large" aria-label="close" data-dismiss="modal"></button>
					 			  </div>									
					  <% end %>
			  </ul>
		  <% end %>
	  </div>

app/views/users/_interview.html.erb
		<div class='column is-2-tablet is-offset-1-tablet is-2-desktop is-offset-1-desktop is-fullwidth-mobile box'>
			<div class='title is-size-5-mobile is-size-6-tablet is-size-4-desktop has-text-centered'>10ケースマラソン</div>
			<% interviews.each_with_index do |interview, i| %>
			  <ul>
				  <div class='subtitle is-size-5 has-text-centered'><%= interview.name %></div>
				  	<% if interview.users_interviews.exists?(user_id: user.id) %>
						 	<div class='subtitle is-size-5 has-text-link has-text-centered'><%= interview.interview_date(user) %></div>
						 	<p class='has-text-centered'>
							  <a class="button is-link modal-button 02" id="modal-btn<%= i %>" data-index=<%= i %>>実施日変更</a>	
							</p>
							<div class='block'></div>

							<div id="users-interview-modal<%= i %>" class="modal">
							<div class="modal-background"></div>
							<div class="modal-content box has-text-centered">
								<p class="subtitle">10ケースマラソン：<%= interview.name %></p>
									<%# form_forのurlでcontrollerとactionを指定する %>
									<%= form_for interview.interview_of_user(user), url: user_users_interview_path(user_id: user.id, id: interview.users_interview_id(user)), html: {method: 'PATCH'}, remote: true do |f| %>  
										<div class="field has-addons">  				
												<%= f.date_field :date, :class => "input is-info", value: Time.now.strftime("%Y-%m-%d") %>								
												<%= f.hidden_field :interview_id, :value => interview.id %>
											<div class="control">
												<%= f.submit '実施日変更', :class => 'button is-link'%>
											</div>
										</div>
									<% end %>
							</div>
							<button class="modal-close is-large" aria-label="close" data-dismiss="modal"></button>
							</div>

					  <% else %>
		 					<p class='has-text-centered'>
							  <a class="button is-danger modal-button 02" id="modal-btn<%= i %>" data-index=<%= i %>>実施日登録</a>
		 					  <div class='block'></div>
		          </p>
								  <div id="users-interview-modal<%= i %>" class="modal">
		  						  <div class="modal-background"></div>
		  							<div class="modal-content box has-text-centered">
      							  <p class="subtitle">10ケースマラソン：<%= interview.name %></p>
										  	<%= form_for [user, users_interview], remote: true do |f| %>
								  				<div class="field has-addons">
										    	    <%= f.date_field :date, :class => "input is-info", value: Time.now.strftime("%Y-%m-%d")%>
										          <%= f.hidden_field :interview_id, :value => interview.id %>
										        <div class="control">
										          <%= f.submit '実施日登録', :class => 'button is-danger'%>
										        </div>
										      </div>
								        <% end %>
							 			</div>
							 			<button class="modal-close is-large" aria-label="close" data-dismiss="modal"></button>
					 			    </div>
						<% end %>
				</ul>
			<% end %>
		</div>

app/views/users/_lesson.html.erb
		<div class="column is-fullwidth-mobile is-6-tablet is-4-desktop is-offset-1-desktop box">
			<div class='title is-size-5-mobile is-size-5-tablet is-size-4-desktop has-text-centered'>考えるエンジン講座</div>
			  <% lessons.each_with_index do |lesson, i| %>
			    <ul>
					  <%= lesson.display_title %>
							<p class='subtitle is-size-5 has-text-centered'><%= lesson.name %></p>
						  <% if lesson.user_id(user) %>
								<p class='subtitle is-size-5 has-text-link has-text-centered'><%= lesson.lesson_date(user) %></p>
						  	<p class='has-text-centered'>
							    <a class="button is-link modal-button 01" id="modal-btn<%= i %>" data-index=<%= i %>>受講日変更</a>	
							  </p>								
								<p class='block'></p>
																
								<div id="users-lesson-modal<%= i %>" class="modal">
								<div class="modal-background"></div>
								<div class="modal-content box has-text-centered">
									<p class="subtitle"><%= lesson.name %></p>
										<%# form_forのurlでcontrollerとactionを指定する %>
										<%= form_for lesson.lesson_of_user(user), url: user_users_lesson_path(user_id: user.id, id: lesson.users_lesson_id(user)), html: {method: 'PATCH'}, remote: true do |f| %>  
											<div class="field has-addons">  				
													<%= f.date_field :date, :class => "input is-info", value: Time.now.strftime("%Y-%m-%d") %>								
													<%= f.hidden_field :lesson_id, :value => lesson.id %>
												<div class="control">
													<%= f.submit '受講日変更', :class => 'button is-link'%>
												</div>
											</div>
										<% end %>
								</div>
								<button class="modal-close is-large" aria-label="close" data-dismiss="modal"></button>
								</div>

						  <% else %>
								<%= render partial: "users/lessonModal", locals: {user: user, users_lesson: users_lesson, lesson: lesson, i: i} %> 
							<% end %>
					</ul>
				<% end %> 
		</div> 

	