config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

#   devise_for :users, path: 'users', controllers: {
#   sessions:      'users/sessions',
#   passwords:     'users/passwords',
#   registrations: 'users/registrations',
#   omniauth_callbacks: 'users/omniauth_callbacks'
# }

  devise_for :admins, path: 'admins', controllers: {
  sessions:      'admins/sessions',
  passwords:     'admins/passwords',
  registrations: 'admins/registrations'
}

  devise_scope :user do
    authenticated :user do
      root :to => 'users#show', as: :authenticated_user_root
    end
    unauthenticated :user do
      root :to => 'users/sessions#new', as: :unauthenticated_user_root
    end
  end

  devise_scope :admin do
    authenticated :admin do
      root :to => 'admins#show', as: :authenticated_admin_root
    end
    unauthenticated :admin do
      root :to => 'admins/sessions#new', as: :unauthenticated_admin_root
    end
  end

  # namespace :admins do
  #   constraints subdomain: 'admins' do
  #     resources :users, only: [:index, :destroy] do
  #       collection do
  #         get 'search'
  #       end
  #     end
  #   end
  # end

  resources :admins, only: [:show] do
    collection do
      get 'search'
    end
  end

  resources :admins_users, only: [:show]

 	resources :users, only: [:show, :edit, :update,] do
    resources :next_lessons, only: [:create, :update]
	  resources :users_lessons, only: [:create, :update]
	  resources :users_interviews, only: [:create, :update]
 	  resources :users_insights, only: [:create, :update]
    resources :users_exams, only: [:create, :update]
    resources :users_practices, only: [:create, :update]
    resources :users_expeditions, only: [:create, :update]
    resources :pictures, only: [:index, :new, :create]
  end

  # resources :insights, only: [:edit, :update]

end

app/models/picture.rb
class Picture < ActiveRecord::Base

  belongs_to :user
  validates_presence_of :user_id, :image

  mount_uploader :image, ImageUploader
  
end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
  before_action :authenticate_user!
  before_action :move_to_session

  def index
    @pictures = Picture.where(user_id: params[:user_id])
  end

  def new
    @picture = Picture.new
  end

  def create
    @picture = Picture.new(picture_params)
    if @picture.save
      redirect_to user_pictures_path(params[:user_id])
    end
  end

  private
  def move_to_session
		@user = User.find(params[:user_id])
		unless current_user.id == @user.id
			redirect_to action: 'show', status: 404
		end
  end
  
  def picture_params
    params.require(:picture).permit(:caption, :image).merge(user_id: params[:user_id])
  end
end

app/helpers/pictures_helper.rb
module PicturesHelper
end

app/views/pictures/index.html.erb
<section class="hero is-fullheight has-text-centered">
 
    <div class='block'></div>
    <h3 class="title has-text-grey">Photo Album</h3>
   
    <h2 class="subtitle">講義写真や読了本を記録しましょう。</h2>
    <h4><%= link_to "Add your photo here",  new_user_picture_path(@user.id), class: "subtitle is-italic has-text-danger" %></h4>
    <div class='block'></div>

    <div class='column is-12'>
    <div class="slider-pro" id="slider1">
      <div class="sp-slides">
      <% @pictures.each do |picture| %>   
        <div class="sp-slide">
          <%= image_tag picture.image.url %>
          <p class="sp-caption"><%= "#{picture.caption}" %></p>
        </div>
      <% end %>
      </div>
    </div>
    </div>
	
</section>

app/views/pictures/new.html.erb
<section class="hero is-fullheight">
  <div class='container has-text-centered'>
      <div class="column is-6 is-offset-3">	
        <h3 class="title has-text-grey is-italic">Add your photo</h3>
        <div class='block'></div>
        <div class="form-group">
          <%= form_for [@user, @picture] do |f| %>

            <%= f.label :caption %>
            <%= f.text_field :caption, :class => 'input is-success'%>

            <%= f.label :image %>
            <%= f.file_field :image, class: "form-control floating-label" %> 
            <figure class="image is-300x300">            
						</figure>

            <%= f.hidden_field :user_id, :value => params[:user_id] %>
            <div class='block'></div>
            <%= f.submit 'Save', :class => 'button is-link'%>

          <% end %>
        </div>
      </div>
  </div>
</section>